repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer

  - repo: local
    hooks:
      - id: build-and-test-package
        name: Build and test package
        entry: python scripts/pre_push_hook.py
        language: python
        pass_filenames: false
        stages: [pre-push]
